## Set the CI/CD variable $KUBE_CONTEXT through the GitLab UI or define it here.
## Replace <FULL_NAME_OF_CLUSTER_MANAGEMENT_PROJECT>:<NAME_YOU_GAVE_YOUR_AGENT>
## with the actual project and agent name.
variables:
  KUBE_CONTEXT: "scalyshop-cluster-management:management-agent"

.base:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v2.1.0"
  before_script:
    - chmod 400 "$KUBECONFIG"   # Workaround for permission issues
    - gl-use-kube-context

stages:
  - diff
  - sync
  - deploy

diff:
  extends: .base
  stage: diff
  environment:
    name: production
    action: prepare
  script:
    - gl-helmfile --file $CI_PROJECT_DIR/helmfile.yaml diff --suppress-secrets
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sync:
  extends: .base
  stage: sync
  environment:
    name: production
  script:
    - gl-ensure-namespace gitlab-managed-apps
    - gl-helmfile --file $CI_PROJECT_DIR/helmfile.yaml sync
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Changed sync to automatic execution

deploy:
  extends: .base
  stage: deploy
  environment:
    name: production
  script:
    - gl-helmfile --file $CI_PROJECT_DIR/helmfile.yaml apply
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
