variables:
  KUBE_CONTEXT: "courses/dat490/students/2025/dat490-2025-9/scalyshop-cluster-management:management-agent"

.base:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v2.1.0"
  before_script:
    - chmod 400 "$KUBECONFIG"
    - gl-use-kube-context

stages:
  - diff
  - sync
  - deploy

diff:
  extends: .base
  tags:
    - test
  stage: diff
  environment:
    name: production
    action: prepare
  script:
    - gl-helmfile --file $CI_PROJECT_DIR/helmfile.yaml diff --suppress-secrets
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "dev"

sync:
  extends: .base
  stage: sync
  tags:
    - test
  environment:
    name: production
  script:
    - gl-ensure-namespace gitlab-managed-apps
    - gl-helmfile --file $CI_PROJECT_DIR/helmfile.yaml sync
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  extends: .base
  stage: deploy
  tags:
    - test
  environment:
    name: production
  script:
    - gl-helmfile --file $CI_PROJECT_DIR/helmfile.yaml apply
  rules:
    - if: $CI_COMMIT_BRANCH ==  $CI_DEFAULT_BRANCH
