repositories:
- name: bitnami
  url: https://bitnami.com

releases:
- name: runner
  namespace: gitlab-managed-apps
  chart: bitnami/mongodb
  version: 0.60.0
  installed: true
  values:
    - values.yaml.gotmpl
