repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
- name: grafana
  namespace: gitlab-managed-apps
  chart: grafana/grafana
  version: 8.10.0
  installed: true
#  values:
#    - values.yaml