storage:
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "standard"

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    cpu: 2
    memory: 4Gi

server:
  service:
    type: LoadBalancer
  extraScrapeConfigs: |
    - job_name: 'kubernetes-services'
      kubernetes_sd_configs:
        - role: service
          namespaces:
            names:
              - scalyshop
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true

prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    retention: "7d"

grafana:
  enabled: false