repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mongodb-sharded
    namespace: gitlab-managed-apps
    chart: bitnami/mongodb-sharded
    version: 9.0.0
    installed: true
    values:
      - values.yaml

#  - name: mongodb-init
#    namespace: gitlab-managed-apps
#    chart: ./mongodb-init
#    installed: true