global:
  security:
    ## @param global.security.allowInsecureImages Allows skipping image verification
    allowInsecureImages: true

image:
  registry: docker.io
  repository: liafonx/mongodb-sharded-arm
  tag: "8.0.5"
  digest: ""

shards: 2

shardsvr:
  dataNode:
    replicaCount: 2

auth:
  enabled: true
  rootPassword: $MONGODB_ROOT_PASSWORD
  replicaSetKey: $MONGODB_REPLICA_SET_KEY

extraEnvVars:
  - name: MONGODB_DATABASE
    value: scalyDB
  - name: MONGODB_USERNAME
    value: scaly
  - name: MONGODB_PASSWORD
    value: scalypw

metrics:
  enabled: true
