shards: 2

shardsvr:
  dataNode:
    replicaCount: 2

auth:
  enabled: true
  rootPassword: $MONGODB_ROOT_PASSWORD
  replicaSetKey: $MONGODB_REPLICA_SET_KEY

extraEnvVars:
  - name: MONGODB_DATABASE
    value: scalyDB
  - name: MONGODB_USERNAME
    value: scaly
  - name: MONGODB_PASSWORD
    value: scalypw

metrics:
  enabled: true
