repositories:
  - name: bitnami
    url: https://github.com/bitnami/charts

releases:
- name: mongodb
  namespace: gitlab-managed-apps
  chart: bitnami/mongodb
  version: 8.0.4
  installed: true
  values:
    - values.yaml
